name: Update

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Update
        run: node main.js
        env:
          token: ${{ secrets.FRIEND_TOKEN }}
      - name: Commit and push if changed
        run: |-
          git diff
          git config user.email "2979986590@qq.com"
          git config user.name "webVueBlog"
          git pull
          git add -A
          git commit -m "Auto update README" || exit 0
          git push
